### ISSUE TITLE
configure ProxyCommand in netcfgbu.toml

### ISSUE THREAD

**Issue by wasabi222** [jeremyschulman/netcfgbu#64]
I have a use case where I want one box doing all of the config backups across several data centers. I also have a jumpbox in each data center that I can use to access the mgmt network. However, in order to do this, I use the ssh config option ProxyCommand to proxy my connection to the network gear through the respective data center's jumpbox. Below is a snippet of my ssh config file:

```
Host !jumpbox.networkandrew.com *.networkandrew.com
    ProxyCommand ssh -W %h:%p andrew@jumpbox.networkandrew.com
```

If I'm able to use the above ProxyCommand in my netcfgbu.toml file, I'll be able to accomplish this.

**Comment by jeremyschulman** [comment]
@wasabi222 - thank you, I believe I can add this using an existing mechanism in the asyncssh library.  I do have a few questions:

Since you have a jumpbox in each datacenter, I am presuming that you would want a mechanism to direct which specific devices go through a specific jumpbox.  For example, if you had four datacenters, you would have four jumpboxes, and all devices in datacenter1 would need to go through "jumpbox1" which all devices in datacenter2 would need to go through "jumbox2", etc.  Is that correct?

Another question: do you current use ssh-agent to connect to the jumpboxes or do you manually provide the password when you do the login?

The current asyncssh library does not read `ssh_config` files, so for now I would add a few constructs to the netcfgbu configuration data model to account for this feature request.  Your answers to the above will help me propose a config-model that we can review together before I proceed with the code.

Thank you.

**Comment by wasabi222** [comment]
Jeremy,

You are correct, each datacenter has one jumpbox, so ideally I'd be able to direct which hosts use which jumpbox, based on region or something similar. 

I use an IdentityFile to use key-based auth for all of the jumpboxes. For instance, that section of my ssh-config looks like this:

Host *.networkandrew.com
    IdentityFile ~/.ssh/id_rsa

I'm happy to answer any other questions you have for me. Thanks for looking into this!

**Comment by jeremyschulman** [comment]
Here is a proposal.  Create new sections that define jump-servers.  Each section block identifies the target server and filters that would be applied to inventory records.  The same filtering mechanism as described in the [Filtering docs](https://github.com/jeremyschulman/netcfgbu/blob/master/docs/usage-filtering.md).

The following examples show how to map inventory records using a host regular expression:

````toml
[[jumpserver]]
   server = "jumpserver.dc1"
   include = ['host=.*\.dc1']

[[jumpserver]]
   server = "jumpserver.dc2"
   include = ['host=.*\.dc2']
````

In my inventory, I define a field-column called `site`, which I obtain from Netbox.  I could then create a config that looked like this:

````toml
[[jumpserver]]
   server = "jumpserver.dc1"
   include = ['site=dc1']

[[jumpserver]]
   server = "jumpserver.dc2"
   include = ['site=dc2']
````

What do you think about the above?

Regarding the IdentityFiles; I would presume that your files are configured with a passphrase.   Would that be correct in your case?  What I am doing in my environment is using ssh-agent and then pre-adding the keys into my environment via the `ssh-add` command.  This mechanism establishes the `SSH_AUTH_SOCK` environment variable.  I do not use the IdentityFile in my `ssh_config`.  I am *presuming* that given this setup I should be able to use asyncssh to create a tunnel with ssh-agent support, and then reach the destined target device.  I will write a small test-program to validate this expected behavior and let you know.

**Comment by jeremyschulman** [comment]
OK, I wrote a short program to validate my presumptive behavior of asyncssh; and it works as I expected (hoped).  🎉

**Comment by jeremyschulman** [comment]
Considering `[[jumphost]]` vs. `[jumpserver]` to be more aligned with ssh_config nomenclature.  Any preference?

**Comment by wasabi222** [comment]
That model makes sense to me and looks good. I have no preference on jumphost versus jumpserver so whichever you prefer.

You are correct in that the keys are configured with a passphrase, which I also use ssh-add to manage. It sounds like this is moving along nicely! Thank you for looking at this so quickly.

**Comment by jeremyschulman** [comment]
Excellent, thank you.  I'll proceed with the `[[jumphost]]` name and should have something in the `develop` branch tomorrow.

**Comment by jeremyschulman** [comment]
code in develop branch now, new docs here:
https://github.com/jeremyschulman/netcfgbu/blob/develop/docs/config-ssh-jumphost.md

**Comment by jeremyschulman** [comment]
completed in develop; waiting merge to master.
